In [1]:
import pandas as pd
import numpy as np
movies=pd.read_csv("imdb_movies.csv",index_col=0)
movies.head()

          movies_name     budget     profit directors_id release_date
movies_id
M001        Movie 001   14000000   27078718         D008   2014-07-01
M002        Movie 002   65000000   -5365617         D015   2017-06-29
M003        Movie 003  181000000  349553886         D022   2014-04-19
M004        Movie 004   30000000   42844497         D029   2024-03-25
M005        Movie 005   15000000   -3541815         D036   2012-09-17

In [3]:
movies.columns

Index(['movies_name', 'budget', 'profit', 'directors_id', 'release_date'], dtype='str')

In [22]:
directors=pd.read_csv("directors.csv")

In [25]:
type(directors)

pandas.DataFrame

In [26]:
directors.columns

Index(['directors_id', 'directors_name'], dtype='str')

In [27]:
directors.rename(columns={"directors_id":"id"},inplace=True)

In [30]:
type(directors)

pandas.DataFrame

In [35]:
movies["budget"].dtype

dtype('int64')

In [39]:
movies["directors_id"].nunique()

40

In [40]:
directors["id"].nunique()

40

In [43]:
data=movies.merge(directors,left_on="directors_id",right_on="id",how="left")

In [44]:
data

,movies_name,budget,profit,directors_id,release_date,id,directors_name
0,Movie 001,14000000,27078718,D008,2014-07-01,D008,Director 008
1,Movie 002,65000000,-5365617,D015,2017-06-29,D015,Director 015
2,Movie 003,181000000,349553886,D022,2014-04-19,D022,Director 022
3,Movie 004,30000000,42844497,D029,2024-03-25,D029,Director 029
4,Movie 005,15000000,-3541815,D036,2012-09-17,D036,Director 036
...,...,...,...,...,...,...,...
115,Movie 116,80000000,118094393,D013,2018-02-09,D013,Director 013
116,Movie 117,60000000,105186922,D020,2019-09-09,D020,Director 020
117,Movie 118,137000000,148861693,D027,2017-12-02,D027,Director 027
118,Movie 119,31000000,48820439,D034,2013-02-20,D034,Director 034
119,Movie 120,19000000,-10224317,D001,2018-03-16,D001,Director 001

In [45]:
data.drop(['id'],axis=1,inplace=True)

In [46]:
data

    movies_name     budget     profit directors_id release_date directors_name
0     Movie 001   14000000   27078718         D008   2014-07-01   Director 008
1     Movie 002   65000000   -5365617         D015   2017-06-29   Director 015
2     Movie 003  181000000  349553886         D022   2014-04-19   Director 022
3     Movie 004   30000000   42844497         D029   2024-03-25   Director 029
4     Movie 005   15000000   -3541815         D036   2012-09-17   Director 036
..          ...        ...        ...          ...          ...            ...
115   Movie 116   80000000  118094393         D013   2018-02-09   Director 013
116   Movie 117   60000000  105186922         D020   2019-09-09   Director 020
117   Movie 118  137000000  148861693         D027   2017-12-02   Director 027
118   Movie 119   31000000   48820439         D034   2013-02-20   Director 034
119   Movie 120   19000000  -10224317         D001   2018-03-16   Director 001

[120 rows x 6 columns]

In [47]:
def square(data):
    return data**2

data["budget"].apply(square)

0        196000000000000
1       4225000000000000
2      32761000000000000
3        900000000000000
4        225000000000000
             ...
115     6400000000000000
116     3600000000000000
117    18769000000000000
118      961000000000000
119      361000000000000
Name: budget, Length: 120, dtype: int64